### PR TITLE
fix: sed error

### PR DESCRIPTION
**Pull request by jay51**
terminal image

### CODE REVIEW

**Comment by Nrechati** [comment]
Thanks for you review and fixes. I actually was going to add New features this morning like thé possibilité to add New class when the project il already created. 
On this Sed this, I believe m'y synthax is the one needed on Darwin MacOS. I'll test your fixés when i'm at work

**Comment by jay51** [comment]
oh, I'm on Linux so, it's probably why. perhaps I could check for os with `uname -s`. is that a thing on osx?

**Comment by Nrechati** [comment]
Actually you can check on the $OSTYPE value to handle those things. like if [[ $OSTYPE == "linux-gnu" ]] then do smth elif [[ $OSTYPE == "darwin"* ]] then do smth else.
To be honest this  project was done in a day to ease my C++ first project and as I know do more and more of C++ I intend to add new feature as I told you and make it more stable and durable. 
I currently have my mind on another project but if you want I've create two new branches 1 called "Reviewing" for general stuff and "linux build" for linux compatibility. Just so you can merge request on things while keeping master clean and stable.

**Comment by Nrechati** [comment]
But, as it's my first ever forked project where I get any reviews and merge request : Thanks you for that :) 
I'll try te go back a few on this project to make it better when i got time, mb next week. I'll stay in touch here on github

**Comment by jay51** [comment]
I closed this and instead opened a pr for linux-buld branch

**Pull request closed without merging**
